# Generated by Django 2.2.16 on 2023-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.CharField(help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес')),
                ('coords', models.CharField(help_text='Координаты адреса', max_length=300, verbose_name='Координаты')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('phone', models.CharField(blank=True, help_text='Ваш номер телефона для связи', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
                ('active', models.BooleanField(default=False, help_text='Объявление одобрено, активно и видно на сайте.', verbose_name='Активно')),
                ('condition', models.CharField(choices=[('OK', 'Здоровое'), ('BD', 'Больное'), ('CR', 'Критическое')], default='OK', max_length=2, verbose_name='Состояние животного')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию найденного животного', upload_to='ads/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите найденное животное', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный возраст животного', max_length=50, verbose_name='Примерный возраст')),
            ],
            options={
                'verbose_name': 'Найден',
                'verbose_name_plural': 'Найдены',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.CharField(help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес')),
                ('coords', models.CharField(help_text='Координаты адреса', max_length=300, verbose_name='Координаты')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию питомца', upload_to='ads/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите вашего потерянного питомца', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный или точный возраст животного', max_length=50, verbose_name='Возраст питомца')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('phone', models.CharField(blank=True, help_text='Ваш номер телефона для связи', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
                ('active', models.BooleanField(default=False, help_text='Объявление одобрено, активно и видно на сайте.', verbose_name='Активно')),
                ('pet_name', models.CharField(blank=True, help_text='Кличка потерянного питомца', max_length=50, verbose_name='Кличка')),
            ],
            options={
                'verbose_name': 'Потерян',
                'verbose_name_plural': 'Потеряны',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
    ]
