# Generated by Django 2.2.19 on 2022-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('location', models.CharField(help_text='Укажите где вы нашли животное', max_length=100, verbose_name='Локация')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию найденного животного', upload_to='ads/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите найденное животное', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный возраст животного', max_length=50, verbose_name='Примерный возраст')),
                ('condition', models.CharField(choices=[('OK', 'Здоровое'), ('BD', 'Больное'), ('CR', 'Критическое')], default='OK', max_length=2, verbose_name='Состояние животного')),
                ('phone', models.CharField(blank=True, help_text='Ваш номер телефона для связи', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('location', models.CharField(help_text='Укажите где вы потеряли питомца', max_length=100, verbose_name='Локация')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию питомца', upload_to='ads/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите вашего потерянного питомца', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный или точный возраст животного', max_length=50, verbose_name='Возраст питомца')),
                ('phone', models.CharField(blank=True, help_text='Ваш номер телефона для связи', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
            ],
        ),
    ]
