# Generated by Django 4.2.1 on 2023-05-11 19:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название вида животного', max_length=50, unique=True, verbose_name='Название вида')),
                ('slug', models.SlugField(help_text='Как будет называться вид животного в URL', unique=True, verbose_name='Слаг')),
                ('icon', models.ImageField(help_text='Иконка для вида животного, будет отображаться на карте.', upload_to='main/img/animal-icons', verbose_name='Иконка')),
                ('default_image', models.ImageField(help_text='Изображение для животного, которое будет отображаться по умолчанию.', upload_to='main/img/default-images', verbose_name='Изображение по умолчанию')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.CharField(blank=True, help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес')),
                ('coords', models.CharField(blank=True, help_text='Координаты адреса', max_length=300, verbose_name='Координаты')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию питомца', upload_to='main/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите вашего потерянного питомца', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный или точный возраст животного', max_length=50, verbose_name='Возраст питомца')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона для связи', max_length=18, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
                ('active', models.BooleanField(default=False, help_text='Объявление одобрено, активно и видно на сайте.', verbose_name='Активно')),
                ('pet_name', models.CharField(blank=True, help_text='Кличка потерянного питомца', max_length=50, verbose_name='Кличка')),
                ('type', models.ForeignKey(help_text='Выберите вид потерянного животного', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost', to='ads.animaltype', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Потерян',
                'verbose_name_plural': 'Потеряны',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.CharField(blank=True, help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес')),
                ('coords', models.CharField(blank=True, help_text='Координаты адреса', max_length=300, verbose_name='Координаты')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона для связи', max_length=18, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Ваша электронная почта для связи', max_length=254, verbose_name='Электронная почта')),
                ('active', models.BooleanField(default=False, help_text='Объявление одобрено, активно и видно на сайте.', verbose_name='Активно')),
                ('condition', models.CharField(choices=[('OK', 'Здоровое'), ('BD', 'Больное'), ('CR', 'Критическое')], default='OK', help_text='В каком состоянии было животное, когда вы его нашли?', max_length=2, verbose_name='Состояние животного')),
                ('image', models.ImageField(blank=True, help_text='Прикрепите фотографию найденного животного', upload_to='main/img', verbose_name='Фотография')),
                ('description', models.TextField(help_text='Опишите найденное животное', verbose_name='Описание')),
                ('age', models.CharField(blank=True, help_text='Примерный возраст животного', max_length=50, verbose_name='Примерный возраст')),
                ('type', models.ForeignKey(help_text='Выберите вид найденного животного', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found', to='ads.animaltype', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Найден',
                'verbose_name_plural': 'Найдены',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
    ]
