# Generated by Django 4.2.1 on 2023-05-24 13:46
from pathlib import Path
import shutil

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


MEDIA_DIR = Path(settings.MEDIA_ROOT)
ICONS_DIR = Path('main/img/animal-icons')
DEFAULT_IMAGES_DIR = Path('main/img/default-images')
STATIC_ICON_DIR = Path(settings.BASE_DIR) / 'static/img/map_icons'

ANIMAL_TYPES = [
    {'name': 'другое', 'slug': 'other', 'icon': str(ICONS_DIR / 'other.png')},
    {'name': 'кот', 'slug': 'cats', 'icon': str(ICONS_DIR / 'cat.png')},
    {'name': 'собака', 'slug': 'dogs', 'icon': str(ICONS_DIR / 'dog.png')}
]


def add_types(apps, schema_editor):
    icons_dir = MEDIA_DIR / ICONS_DIR
    default_images_dir = MEDIA_DIR / DEFAULT_IMAGES_DIR
    icons_dir.mkdir(parents=True, exist_ok=True)
    default_images_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(STATIC_ICON_DIR, icons_dir, dirs_exist_ok=True)

    animal_type_model = apps.get_model('ads', 'AnimalType')
    for animal_type in ANIMAL_TYPES:
        new_animal_type = animal_type_model(**animal_type)
        new_animal_type.save()


def remove_types(apps, schema_editor):
    animal_type_model = apps.get_model('ads', 'AnimalType')
    for animal_type in ANIMAL_TYPES:
        try:
            animal_type_model.objects.get(**animal_type).delete()
        except ObjectDoesNotExist:
            print(f"Warning: Animal type "
                  f"{animal_type.get('name')} doesn't exists. Skipped.")


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_types, remove_types)
    ]
