# Generated by Django 2.2.19 on 2022-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='name',
            field=models.CharField(blank=True, help_text='Кличка питомца', max_length=50, verbose_name='Имя'),
        ),
    ]
