# Generated by Django 2.2.16 on 2023-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='address',
            field=models.CharField(blank=True, help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='found',
            name='coords',
            field=models.CharField(blank=True, help_text='Координаты адреса', max_length=300, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='found',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите фотографию найденного животного', upload_to='main/img', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='address',
            field=models.CharField(blank=True, help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='coords',
            field=models.CharField(blank=True, help_text='Координаты адреса', max_length=300, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепите фотографию питомца', upload_to='main/img', verbose_name='Фотография'),
        ),
    ]
