# Generated by Django 4.2.1 on 2023-05-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20230504_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название вида животного', max_length=50, unique=True, verbose_name='Название вида')),
                ('slug', models.SlugField(help_text='Как будет называться вид животного в URL', unique=True, verbose_name='Слаг')),
                ('icon', models.ImageField(height_field='height', help_text='Иконка для вида животного, будет отображаться на карте.', upload_to='main/img/animal-icons', verbose_name='Иконка', width_field='weight')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
            },
        ),
        migrations.AlterField(
            model_name='found',
            name='condition',
            field=models.CharField(choices=[('OK', 'Здоровое'), ('BD', 'Больное'), ('CR', 'Критическое')], default='OK', help_text='В каком состоянии было животное, когда вы его нашли?', max_length=2, verbose_name='Состояние животного'),
        ),
        migrations.AddField(
            model_name='found',
            name='type',
            field=models.ForeignKey(help_text='Выберите вид найденного животного', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found', to='ads.animaltype', verbose_name='Вид животного'),
        ),
        migrations.AddField(
            model_name='lost',
            name='type',
            field=models.ForeignKey(help_text='Выберите вид потерянного животного', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost', to='ads.animaltype', verbose_name='Вид животного'),
        ),
    ]
