# Generated by Django 4.2.1 on 2023-06-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='open',
            field=models.BooleanField(default=True, help_text='Объявление открыто пользователем', verbose_name='Открыто'),
        ),
        migrations.AddField(
            model_name='lost',
            name='open',
            field=models.BooleanField(default=True, help_text='Объявление открыто пользователем', verbose_name='Открыто'),
        ),
    ]
