# Generated by Django 2.2.19 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_lost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='name',
            field=models.CharField(default='aaa', max_length=50, verbose_name='Ваше имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='pet_name',
            field=models.CharField(blank=True, help_text='Кличка потерянного питомца', max_length=50, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
    ]
