# Generated by Django 4.2.1 on 2023-10-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_add_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое сообщения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('checked', models.BooleanField(default=False, verbose_name='Просмотрено?')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='found',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='coords',
        ),
        migrations.AddField(
            model_name='found',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='found',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='found',
            name='open',
            field=models.BooleanField(default=True, help_text='Объявление открыто пользователем', verbose_name='Открыто'),
        ),
        migrations.AddField(
            model_name='lost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='lost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='lost',
            name='open',
            field=models.BooleanField(default=True, help_text='Объявление открыто пользователем', verbose_name='Открыто'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='found',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='found',
            index=models.Index(fields=['active', 'open'], name='ads_found_active_cd0f83_idx'),
        ),
        migrations.AddIndex(
            model_name='found',
            index=models.Index(fields=['active', 'open', 'latitude', 'longitude'], name='ads_found_active_3e61a8_idx'),
        ),
        migrations.AddIndex(
            model_name='lost',
            index=models.Index(fields=['active', 'open'], name='ads_lost_active_460209_idx'),
        ),
        migrations.AddIndex(
            model_name='lost',
            index=models.Index(fields=['active', 'open', 'latitude', 'longitude'], name='ads_lost_active_6f81a2_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.dialog', verbose_name='Диалог'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='advertisement_found',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.found', verbose_name='Тип объявления: нашелся'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='advertisement_lost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.lost', verbose_name='Тип объявления: потерялся'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_ad_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления из диалога'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_ad_questioner', to=settings.AUTH_USER_MODEL, verbose_name='Задающий вопросы'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'checked'], name='recipient checked idx'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('advertisement_found', None), ('advertisement_lost__isnull', False)), models.Q(('advertisement_found__isnull', False), ('advertisement_lost', None)), _connector='OR'), name='dialog_advertisement_constraint'),
        ),
    ]
