# Generated by Django 4.2.1 on 2023-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_animaltype_alter_found_condition_found_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='icon',
            field=models.ImageField(help_text='Иконка для вида животного, будет отображаться на карте.', upload_to='main/img/animal-icons', verbose_name='Иконка'),
        ),
    ]
