# Generated by Django 2.2.19 on 2022-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20220913_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativearea',
            name='country',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='admin_area',
        ),
        migrations.RemoveField(
            model_name='street',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='location',
        ),
        migrations.AddField(
            model_name='lost',
            name='address',
            field=models.CharField(default=123, help_text='Укажите адрес где потеряли питомца', max_length=300, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='coords',
            field=models.CharField(default=123, help_text='Координаты адреса', max_length=300, verbose_name='Координаты'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AdministrativeArea',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
