# Generated by Django 4.2.1 on 2023-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_animaltype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='default_image',
            field=models.ImageField(default=123, help_text='Изображение для животного, которое будет отображаться по умолчанию.', upload_to='main/img/default-images', verbose_name='Изображение по умолчанию'),
            preserve_default=False,
        ),
    ]
