# Generated by Django 2.2.19 on 2022-09-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20220922_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='found',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='lost',
            options={'ordering': ['-pub_date']},
        ),
    ]
