# Generated by Django 4.2.1 on 2023-08-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='advertisement_found',
        ),
        migrations.RemoveField(
            model_name='message',
            name='advertisement_lost',
        ),
    ]
