# Generated by Django 4.2.1 on 2023-08-21 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_found', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.found', verbose_name='Тип объявления: нашелся')),
                ('advertisement_lost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.lost', verbose_name='Тип объявления: потерялся')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_ad_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления из диалога')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_ad_questioner', to=settings.AUTH_USER_MODEL, verbose_name='Задающий вопросы')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.dialog', verbose_name='Диалог'),
            preserve_default=False,
        ),
    ]
