# Generated by Django 4.2.1 on 2023-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_dialog_message_dialog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='found',
            index=models.Index(fields=['active', 'open'], name='ads_found_active_cd0f83_idx'),
        ),
        migrations.AddIndex(
            model_name='lost',
            index=models.Index(fields=['active', 'open'], name='ads_lost_active_460209_idx'),
        ),
        migrations.AddConstraint(
            model_name='dialog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('advertisement_found', None), ('advertisement_lost__isnull', False)), models.Q(('advertisement_found__isnull', False), ('advertisement_lost', None)), _connector='OR'), name='dialog_advertisement_constraint'),
        ),
    ]
