# Generated by Django 4.2.1 on 2023-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_found_ads_found_active_cd0f83_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'checked'], name='recipient checked idx'),
        ),
    ]
