repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: 2.0.1
  hooks:
    - id: poetry-check

- repo: local
  hooks:
    - id: django-test
      name: django-test
      entry: bash -c "python3 manage.py test"
      always_run: true
      pass_filenames: false
      language: system
