# For development purposes only
services:

  pet-alert-redis:
    image: redis
    ports:
      - "6379:6379"

  pet-alert-db:
    image: postgres:17.2-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - config/.env
    ports:
      - "5432:5432"

  pet-alert-worker:
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    entrypoint: ["bash", "./infra/entrypoint_worker.sh"]
    volumes:
#      - static_volume:/app/static/
#      - media_volume:/app/media/
      - ./server/static:/app/static/
      - ./media:/app/media/
    depends_on:
      - pet-alert-db
      - pet-alert-redis
    env_file:
      - config/.env
    environment:
      DJANGO_DATABASE_HOST: pet-alert-db
      EMAIL_HOST: pet-alert-mailpit
      REDIS_HOST: pet-alert-redis

  pet-alert-mailpit:
    image: axllent/mailpit
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1



volumes:
  database:
  static_volume:
  media_volume:
