name: petalert

services:

  database:
    image: postgres:18.3-alpine
    volumes:
      - database:/var/lib/postgresql/
    env_file:
      - ../config/.env
    restart: always

  backend-prepare:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_backend_prepare.sh
    volumes:
      - /srv/pet-alert/static:/app/static/
      - /srv/pet-alert/media:/app/media/
    depends_on:
      database:
        condition: service_started
    env_file:
      - ../config/.env

  redis:
    image: redis
    restart: always

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_backend.sh
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /srv/pet-alert/static:/app/static/
      - /srv/pet-alert/media:/app/media/
    depends_on:
      backend-prepare:
        condition: service_completed_successfully
      database:
        condition: service_started
    env_file:
      - ../config/.env

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_worker.sh
    restart: always
    volumes:
      - /srv/pet-alert/static:/app/static/
      - /srv/pet-alert/media:/app/media/
    depends_on:
      backend-prepare:
        condition: service_completed_successfully
      backend:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ../config/.env

  ws:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    entrypoint: infra/entrypoint_ws.sh
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - /srv/pet-alert/static:/app/static/
      - /srv/pet-alert/media:/app/media/
    depends_on:
      backend-prepare:
        condition: service_completed_successfully
      database:
        condition: service_started
    env_file:
      - ../config/.env

volumes:
  database:
