version: '3.8'

services:
  db:
    image: postgres:16-bookworm
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Moscow
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./.data/:/.data/
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Moscow
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ${PET_MAIN_NGINX_CONF-./nginx/nginx_pet_alert.template}:/etc/nginx/templates/default.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/bot.conf:/etc/nginx/conf.d/bot.conf
      - ./nginx/bot_include.conf:/etc/nginx/vhosts-includes/bot.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    env_file:
      - ../.env
    depends_on:
      - web
    environment:
      - TZ=Europe/Moscow
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    env_file:
      - ../.env
    depends_on:
      - nginx
    environment:
      - TZ=Europe/Moscow
    command: certonly --webroot -w /var/www/certbot --force-renewal --email admin@${WEBSITE_HOST} -d ${WEBSITE_HOST} --agree-tos

volumes:
  database:
  static_volume:
  media_volume:
  certbot_conf:
  certbot_www:
