version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow
  web:
    build: ../pet_alert
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - web
    environment:
      - TZ=Europe/Moscow
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - nginx
    environment:
      - TZ=Europe/Moscow
    command: certonly --webroot -w /var/www/certbot --force-renewal --email admin@pet-alert.ru -d pet-alert.ru --agree-tos

volumes:
  database:
  static_volume:
  media_volume:
  certbot_conf:
  certbot_www: