# Generated by Django 5.1.6 on 2025-03-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название вида животного",
                        max_length=50,
                        unique=True,
                        verbose_name="Название вида",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Как будет называться вид животного в URL",
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Иконка для вида животного, будет отображаться на карте.",
                        upload_to="main/img/animal-icons",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "default_image",
                    models.ImageField(
                        help_text="Изображение для животного, которое будет отображаться по умолчанию.",  # noqa
                        upload_to="main/img/default-images",
                        verbose_name="Изображение по умолчанию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид животного",
                "verbose_name_plural": "Виды животных",
            },
        ),
        migrations.CreateModel(
            name="Found",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания объявления"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Укажите адрес", max_length=300, verbose_name="Адрес"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Широта"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Объявление одобрено, активно и видно на сайте.",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "open",
                    models.BooleanField(
                        default=True,
                        help_text="Объявление открыто пользователем",
                        verbose_name="Открыто",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("OK", "Здоровое"), ("BD", "Больное"), ("CR", "Критическое")],
                        default="OK",
                        help_text="В каком состоянии было животное, когда вы его нашли?",
                        max_length=2,
                        verbose_name="Состояние животного",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Прикрепите фотографию найденного животного",
                        upload_to="main/img",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Опишите найденное животное", verbose_name="Описание"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        help_text="Примерный возраст животного",
                        max_length=50,
                        verbose_name="Примерный возраст",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор объявления о находке",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="found_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Выберите вид найденного животного",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="found",
                        to="ads.animaltype",
                        verbose_name="Вид животного",
                    ),
                ),
            ],
            options={
                "verbose_name": "Найден",
                "verbose_name_plural": "Найдены",
                "ordering": ["-pub_date"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["active", "open"], name="ads_found_active_cd0f83_idx"),
                    models.Index(
                        fields=["active", "open", "latitude", "longitude"],
                        name="ads_found_active_3e61a8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания объявления"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Укажите адрес", max_length=300, verbose_name="Адрес"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Широта"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Прикрепите фотографию питомца",
                        upload_to="main/img",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Опишите вашего потерянного питомца", verbose_name="Описание"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        help_text="Примерный или точный возраст питомца",
                        max_length=50,
                        verbose_name="Возраст питомца",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Объявление одобрено, активно и видно на сайте.",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "open",
                    models.BooleanField(
                        default=True,
                        help_text="Объявление открыто пользователем",
                        verbose_name="Открыто",
                    ),
                ),
                (
                    "pet_name",
                    models.CharField(
                        blank=True,
                        help_text="Кличка потерянного питомца",
                        max_length=50,
                        verbose_name="Кличка",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор объявления о пропаже",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Выберите вид потерянного питомца",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost",
                        to="ads.animaltype",
                        verbose_name="Вид животного",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потерян",
                "verbose_name_plural": "Потеряны",
                "ordering": ["-pub_date"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["active", "open"], name="ads_lost_active_460209_idx"),
                    models.Index(
                        fields=["active", "open", "latitude", "longitude"],
                        name="ads_lost_active_6f81a2_idx",
                    ),
                ],
            },
        ),
    ]
