# Generated by Django 5.1.7 on 2025-05-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advertisements",
                to="ads.animaltype",
                verbose_name="Вид животного",
            ),
        ),
        migrations.AddIndex(
            model_name="advertisement",
            index=models.Index(fields=["active", "open"], name="ads_adverti_active_1c32d3_idx"),
        ),
        migrations.AddIndex(
            model_name="advertisement",
            index=models.Index(
                fields=["active", "open", "latitude", "longitude"],
                name="ads_adverti_active_26bc50_idx",
            ),
        ),
    ]
