# Generated by Django 5.1.7 on 2025-05-29 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_add_types"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnimalType",
            new_name="AnimalSpecies",
        ),
        migrations.RenameField(
            model_name="advertisement",
            old_name="type",
            new_name="species",
        ),
    ]
