# Generated by Django 5.1.7 on 2025-05-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0004_rename_animaltype_animalspecies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="species",
            field=models.ForeignKey(
                help_text="Выберите вид животного",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advertisements",
                to="ads.animalspecies",
                verbose_name="Вид животного",
            ),
        ),
    ]
