# Generated by Django 4.2.1 on 2023-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Будет использоваться для логина на сайте",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Ваше имя, будет видно в объявлениях и в личных сообщениях",
                max_length=150,
                verbose_name="first name",
            ),
        ),
    ]
