# Generated by Django 4.2.1 on 2023-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_contact_email_user_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Используется для отправки сообщений пользователям в telegram",
                null=True,
                verbose_name="Telegram ID пользователя",
            ),
        ),
    ]
