# Generated by Django 4.2.1 on 2023-11-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_dialog_message_remove_found_coords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="found",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Укажите адрес",
                max_length=300,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="found",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания объявления"
            ),
        ),
        migrations.AlterField(
            model_name="lost",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Укажите адрес",
                max_length=300,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="lost",
            name="age",
            field=models.CharField(
                blank=True,
                help_text="Примерный или точный возраст питомца",
                max_length=50,
                verbose_name="Возраст питомца",
            ),
        ),
        migrations.AlterField(
            model_name="lost",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания объявления"
            ),
        ),
        migrations.AlterField(
            model_name="lost",
            name="type",
            field=models.ForeignKey(
                help_text="Выберите вид потерянного питомца",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lost",
                to="ads.animaltype",
                verbose_name="Вид животного",
            ),
        ),
    ]
