# Generated by Django 5.1.7 on 2026-02-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs",
                        to="ads.advertisement",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор объявления из диалога",
                    ),
                ),
                (
                    "questioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs_questioner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Задающий вопросы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диалог",
                "verbose_name_plural": "Диалоги",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(max_length=500, verbose_name="Содержимое сообщения")),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("checked", models.BooleanField(default=False, verbose_name="Просмотрено?")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messenger.dialog",
                        verbose_name="Диалог",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("author", "questioner", "advertisement"),
                name="dialog_unique_together_author_questioner_adv",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.CheckConstraint(
                condition=models.Q(("author", models.F("questioner")), _negated=True),
                name="dialog_author_cant_message_himself",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["recipient", "checked"], name="recipient checked idx"),
        ),
    ]
