# Generated by Django 5.1.6 on 2025-03-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "advertisement_found",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ads.found",
                        verbose_name="Тип объявления: нашелся",
                    ),
                ),
                (
                    "advertisement_lost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ads.lost",
                        verbose_name="Тип объявления: потерялся",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор объявления из диалога",
                    ),
                ),
                (
                    "questioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs_questioner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Задающий вопросы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диалог",
                "verbose_name_plural": "Диалоги",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(max_length=500, verbose_name="Содержимое сообщения")),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("checked", models.BooleanField(default=False, verbose_name="Просмотрено?")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messenger.dialog",
                        verbose_name="Диалог",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("advertisement_found", None), ("advertisement_lost__isnull", False)),
                    models.Q(("advertisement_found__isnull", False), ("advertisement_lost", None)),
                    _connector="OR",
                ),
                name="dialog_advertisement_constraint",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["recipient", "checked"], name="recipient checked idx"),
        ),
    ]
