# Generated by Django 5.1.7 on 2025-05-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialogs_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления из диалога",
            ),
        ),
        migrations.AddField(
            model_name="dialog",
            name="questioner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialogs_questioner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Задающий вопросы",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="dialog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messenger.dialog",
                verbose_name="Диалог",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("author", "questioner", "advertisement"),
                name="dialog_unique_together_author_questioner_adv",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.CheckConstraint(
                condition=models.Q(("author", models.F("questioner")), _negated=True),
                name="dialog_author_cant_message_himself",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["recipient", "checked"], name="recipient checked idx"),
        ),
    ]
