# Generated by Django 5.1.6 on 2025-03-16 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_add_types"),
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dialog",
            name="dialog_advertisement_constraint",
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("advertisement_found", None), ("advertisement_lost__isnull", False)),
                    models.Q(("advertisement_found__isnull", False), ("advertisement_lost", None)),
                    _connector="OR",
                ),
                name="dialog_related_adv_not_null_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("author", "questioner", "advertisement_lost", "advertisement_found"),
                name="dialog_unique_together_author_questioner_adv",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.CheckConstraint(
                condition=models.Q(("author", models.F("questioner")), _negated=True),
                name="dialog_author_cant_message_himself",
            ),
        ),
    ]
