# Generated by Django 5.1.6 on 2025-03-16 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_add_types"),
        ("messenger", "0002_remove_dialog_dialog_advertisement_constraint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dialog",
            name="dialog_unique_together_author_questioner_adv",
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("author", "questioner", "advertisement_lost"),
                name="dialog_unique_together_author_questioner_lost_adv",
            ),
        ),
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("author", "questioner", "advertisement_found"),
                name="dialog_unique_together_author_questioner_found_adv",
            ),
        ),
    ]
